# Generated by Django 5.2.12 on 2026-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_assigned_vehicle_order_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Điểm giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ tài xế'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tài xế'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán')], default='UNPAID', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Điểm nhận hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_size',
            field=models.CharField(blank=True, choices=[('SMALL', 'Nhỏ (S)'), ('MEDIUM', 'Vừa (M)'), ('LARGE', 'To (L)')], max_length=20, null=True, verbose_name='Kích cỡ hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(blank=True, choices=[('FASHION', 'Thời Trang'), ('COSMETICS', 'Mĩ Phẩm'), ('ELECTRONICS', 'Điện Tử'), ('HOUSEHOLD', 'Gia Dụng'), ('FOOD', 'Thực Phẩm'), ('OTHER', 'Khác')], max_length=50, null=True, verbose_name='Loại hàng hóa'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên người nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại người nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá tiền'),
        ),
    ]
