# Generated by Django 5.2.12 on 2026-03-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_delivery_point_order_driver_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do hủy chuyến'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hủy'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_cancel_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tài xế hủy chuyến'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_cancel_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại tài xế hủy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In progress'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
    ]
